### ISSUE TITLE
The server implementation for Linux is needed

### ISSUE THREAD

**Issue by nxtreaming** [BarbaTunnelCoder/BarbaTunnel#4]
Almost all servers are deployed in Linux(unix),  so it's a good reason to implement the linux verison of BarbaTunnel server.

Thanks.

**Comment by BarbaTunnelCoder** [comment]
I agree, It is an old project and I just moved it from codeplex and fix some issues. I wish I had time and make it as independent VPN. but unfortunately, I have no time to work on it more.
